export enum CURRENCY_CODES {
	USD = 'USD',
	EUR = 'EUR',
	INR = 'INR',
	PLAY_COINS = 'PLAY_COINS',
	PLAY_CASH = 'PLAY_CASH',
	BHC = 'BHC',
	GEMS = 'GEMS',
}
export enum COIN_TYPE {
	WINNING_COINS = 'WINNING_COINS',
	BONUS_COINS = 'BONUS_COINS',
	DEPOSIT_COINS = 'DEPOSIT_COINS',
	GEMS = 'GEMS',
}

export const CURRENCY_SYMBOLS_MAP: Record<CURRENCY_CODES, string> = {
	[CURRENCY_CODES.USD]: '$',
	[CURRENCY_CODES.EUR]: '€',
	[CURRENCY_CODES.INR]: '₹',
	[CURRENCY_CODES.PLAY_COINS]: '💰',
	[CURRENCY_CODES.PLAY_CASH]: '💸',
	[CURRENCY_CODES.BHC]: 'BHC',
	[CURRENCY_CODES.GEMS]: '💎',
}
